FROM python:3.9-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "src/control_room/app.py"]
